script

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -77,25 +77,22 @@ runs:
         FLAT_NAMING: "${{ inputs.flat_naming }}"
       run: |
         set -e
-        chmod +x "${{ github.action_path }}/src/scripts/lokalise_download.sh"
-
-        . "${{ github.action_path }}/src/scripts/lokalise_download.sh"
-
-        download_files "${{ inputs.project_id }}" "${{ inputs.api_token }}"
-
-        if [ $? -ne 0 ]; then
-          echo "Error during file download"
+        
+        CMD_PATH="${{ github.action_path }}/bin/lokalise_download"
+        chmod +x "$CMD_PATH"
+        $("$CMD_PATH") || {
+          echo "Error: lokalise_download script failed with exit code $?"
           echo "has_changes=false" >> $GITHUB_OUTPUT
           exit 1
-        fi
+        }
 
-        if detect_changed_files; then
-          echo "Translation file changes detected after pulling from Lokalise"
-          echo "has_changes=true" >> $GITHUB_OUTPUT
-        else
-          echo "No translation file changes detected after pulling from Lokalise"
+        CMD_PATH="${{ github.action_path }}/bin/detect_changed_files"
+        chmod +x "$CMD_PATH"
+        $("$CMD_PATH") || {
+          echo "Error: detect_changed_files script failed with exit code $?"
           echo "has_changes=false" >> $GITHUB_OUTPUT
-        fi
+          exit 1
+        }
 
     - name: Commit changes
       id: create-commit
@@ -110,15 +107,13 @@ runs:
       shell: bash
       run: |
         set -e
-        chmod +x "${{ github.action_path }}/src/scripts/commit_changes.sh"
-        
-        . "${{ github.action_path }}/src/scripts/commit_changes.sh"
-        
-        if commit_and_push_changes; then
-          echo "commit_created=true" >> $GITHUB_OUTPUT
-        else
-          echo "commit_created=true" >> $GITHUB_OUTPUT
-        fi
+        CMD_PATH="${{ github.action_path }}/bin/commit_changes"
+        chmod +x "$CMD_PATH"
+        $("$CMD_PATH") || {
+          echo "Error: commit_changes script failed with exit code $?"
+          echo "has_changes=false" >> $GITHUB_OUTPUT
+          exit 1
+        }
         
     - name: Create or Update Pull Request
       if: steps.pull-files.outputs.has_changes == 'true' && steps.create-commit.outputs.commit_created == 'true'
